name: Solidity tests on Morpho Compound

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "contracts/*"
      - "contracts/compound/**"
      - "test/compound/**"
      - "*.lock"
      - "Makefile"
      - "remappings.txt"
      - ".github/workflows/ci-foundry-compound.yml"
  pull_request:
    paths:
      - "lib/**"
      - "contracts/*"
      - "contracts/compound/**"
      - "test/compound/**"
      - "*.lock"
      - "Makefile"
      - "remappings.txt"
      - ".github/workflows/ci-foundry-compound.yml"

jobs:
  morpho-compound:
    if: "! github.event.pull_request.draft"
    name: Morpho-Compound
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.CI_PRIVATE_KEY }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Node dependencies cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: make test PROTOCOL=compound NETWORK=eth-mainnet
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
